data:
  path: "bias_detector/.data/processed/allergenchipchallenge-cleaned_data.csv"
  target_presence: "allergy_present"
  target_severity: "allergy_severity"
  test_size: 0.2
  random_state: 37

model:
  base_type: "RandomForest"
  ensemble_type: "Stacking"
  penalty: "l1"
  random_state: 37

paths:
  model_dir: "bias_detector/models/allergy_model.pkl"
  figures_dir: "bias_detector/.figures/"